### ISSUE TITLE
Where does the variable ServerlessRestApi come from in the generated serverless.template file?

### ISSUE THREAD

**Issue by macfarmw** [aws/aws-toolkit-visual-studio#173]
When I create a new app using the  toolkit template "AWS Serverless Application with Tests (.NET Core - C#)" there is a line at the end of the generated serverless.template file.
```
Outputs: 
    ApiURL: 
        Description: API endpoint URL
        Value: 
            Fn::Sub: 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
```
**Note:** I have converted to YAML syntax but otherwise this is it.

This was working fine and the variable _ServerlessRestApi_ contained the ID of the API gateway that was generated to support calls to the Lambda functions.

Since then I added an explicit entry in the template for the API.
```
MarketingContactFormsApi:
    Type: AWS::Serverless::Api
    Properties:
        StageName: Prod
        Cors:
            AllowMethods: "'POST, GET'"
            AllowOrigin: "'*'"
```
And then reference this named API from the Lambda events like this:
```
Events: 
    GetResource: 
        Type: Api
        Properties: 
            Path: /{Id}
            Method: GET
            RestApiId:
                Ref: MarketingContactFormsApi
```
After making that change the dotnet lambda deploy-serverless command now fails with this error.
`Failed to create CloudFormation change set: Unresolved resource dependencies [ServerlessRestApi] in the Outputs block of the template`

So apparently that variable is no longer being set. Where does this variable come from and how can I set it to the ID of my named API?

**Comment by awschristou** [comment]
It might be a syntax issue - https://github.com/aws/serverless-application-model/issues/104 contains a similar output sample that may help out

**Comment by macfarmw** [comment]
The syntax was OK but that variable just not get set with an explicit API. I used the follow method to set the variable myself.

## Before
```
Outputs: 
    ApiURL: 
        Description: API endpoint URL
        Value:
            Fn::Sub: 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'      
```
## After
```
Outputs: 
    ApiURL: 
        Description: API endpoint URL
        Value: !Sub
            - 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
            - { ServerlessRestApi: !Ref MarketingContactFormsApi }
```
I found this syntax in the documentation for the intrinsic Sub function.
[Fn::Sub - AWS Cloud Formation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html)
